export function generateResponse(params: any) {
  console.log('params44444', params);
  const wholedata: any = {
    "本浦冷轧2#重卷机组": {
      name: "本浦冷轧2#重卷机组",
      __type: {
        carbonEmission: "碳排放量情况",
        powerQuantity: "用电情况",
        operatingParameterList: "运行参数情况",
        maintainRecordList: "维护记录",
      },
      maintainRecordList: [
        {
          date: "202301",
          maintainRecord: "11检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202302",
          maintainRecord: "11更换酸液",
          faultDescription: "0%",
        },
        {
          date: "202303",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202304",
          maintainRecord: "更换酸液",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202305",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202306",
          maintainRecord: "清理处理槽",
          faultDescription: "0%",
        },
        {
          date: "202307",
          maintainRecord: "检查酸液浓度",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202308",
          maintainRecord: "更换酸液",
          faultDescription: "0%",
        },
        {
          date: "202309",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202310",
          maintainRecord: "更换酸液",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202311",
          maintainRecord: "检查处理设备",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202312",
          maintainRecord: "年终大修",
          faultDescription: "0%",
        },
      ],
      operatingParameterList: [
        {
          date: "202301",
          ratedPower: "145",
          runningTime: "2",
        },
        {
          date: "202302",
          ratedPower: "150",
          runningTime: "2.5",
        },
        {
          date: "202303",
          ratedPower: "155",
          runningTime: "2.5",
        },
        {
          date: "202304",
          ratedPower: "160",
          runningTime: "2.5",
        },
        {
          date: "202305",
          ratedPower: "165",
          runningTime: "2.5",
        },
        {
          date: "202306",
          ratedPower: "70",
          runningTime: "2.5",
        },
        {
          date: "202307",
          ratedPower: "75",
          runningTime: "2.5",
        },
        {
          date: "202308",
          ratedPower: "65",
          runningTime: "2.5",
        },
        {
          date: "202309",
          ratedPower: "70",
          runningTime: "2.5",
        },
        {
          date: "202310",
          ratedPower: "155",
          runningTime: "12.5",
        },
        {
          date: "202311",
          ratedPower: "45",
          runningTime: "2.5",
        },
        {
          date: "202312",
          ratedPower: "65",
          runningTime: "2.5",
        },
      ],
      carbonEmission: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "carbonEmissions",
            dataList: [
              "13607.99",
              "2817.65",
              "3676.67",
              "3195.61",
              "3023.83",
              "3023.83",
              "3264.37",
              "3161.26",
              "3092.58",
              "3264.37",
              "3333.11",
              "3882.87",
            ],
            dataType: "Bar",
            dataName: "碳排放量",
            dataUnit: "吨",
          },
          {
            dataTag: "yoy",
            dataList: [
              Math.random() * 10,
              -11,
              Math.random() * 10,
              Math.random() * 10,
              Math.random() * 10,
              -10.2,
              Math.random() * 10,
              Math.random() * 10,
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "同比",
            dataUnit: "%",
          },
        ],
      },
      powerQuantity: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "power",
            dataList: [
              "1259.89",
              "1202.96",
              "1264.84",
              "1230.18",
              "1217.81",
              "1217.81",
              "1235.14",
              "1227.72",
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "实际电量",
            dataUnit: "万kwh",
          },
          {
            dataTag: "powerForecasting",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "823.09",
              "783.46",
              "882.54",
              "922.17",
              "239.25",
            ],
            dataType: "Line",
            dataName: "预测电量",
            dataUnit: "万kwh",
          },
        ],
      },
    },
    "本浦冷轧3#重卷机组": {
      name: "本浦冷轧3#重卷机组",
      __type: {
        carbonEmission: "碳排放量情况",
        powerQuantity: "用电情况",
        operatingParameterList: "运行参数情况",
        maintainRecordList: "维护记录",
      },
      maintainRecordList: [
        {
          date: "202301",
          maintainRecord: "11检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202302",
          maintainRecord: "11更换酸液",
          faultDescription: "0%",
        },
        {
          date: "202303",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202304",
          maintainRecord: "更换酸液",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202305",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202306",
          maintainRecord: "清理处理槽",
          faultDescription: "0%",
        },
        {
          date: "202307",
          maintainRecord: "检查酸液浓度",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202308",
          maintainRecord: "更换酸液",
          faultDescription: "0%",
        },
        {
          date: "202309",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202310",
          maintainRecord: "更换酸液",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202311",
          maintainRecord: "检查处理设备",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202312",
          maintainRecord: "年终大修",
          faultDescription: "0%",
        },
      ],
      operatingParameterList: [
        {
          date: "202301",
          ratedPower: "245",
          runningTime: "2.5",
        },
        {
          date: "202302",
          ratedPower: "250",
          runningTime: "2.5",
        },
        {
          date: "202303",
          ratedPower: "255",
          runningTime: "2.5",
        },
        {
          date: "202304",
          ratedPower: "260",
          runningTime: "2.5",
        },
        {
          date: "202305",
          ratedPower: "265",
          runningTime: "2.5",
        },
        {
          date: "202306",
          ratedPower: "70",
          runningTime: "2.5",
        },
        {
          date: "202307",
          ratedPower: "75",
          runningTime: "2.5",
        },
        {
          date: "202308",
          ratedPower: "65",
          runningTime: "2.5",
        },
        {
          date: "202309",
          ratedPower: "70",
          runningTime: "2.5",
        },
        {
          date: "202310",
          ratedPower: "55",
          runningTime: "2.5",
        },
        {
          date: "202311",
          ratedPower: "45",
          runningTime: "2.5",
        },
        {
          date: "202312",
          ratedPower: "65",
          runningTime: "2.5",
        },
      ],
      carbonEmission: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "carbonEmissions",
            dataList: [
              "3607.99",
              "2817.65",
              "3676.67",
              "3195.61",
              "3023.83",
              "3023.83",
              "3264.37",
              "3161.26",
              "3092.58",
              "3264.37",
              "3333.11",
              "3882.87",
            ],
            dataType: "Bar",
            dataName: "碳排放量",
            dataUnit: "吨",
          },
          {
            dataTag: "yoy",
            dataList: [
              Math.random() * 10,
              -11,
              Math.random() * 10,
              Math.random() * 10,
              Math.random() * 10,
              -10.2,
              Math.random() * 10,
              Math.random() * 10,
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "同比",
            dataUnit: "%",
          },
        ],
      },
      powerQuantity: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "power",
            dataList: [
              "1259.89",
              "1202.96",
              "1264.84",
              "1230.18",
              "1217.81",
              "1217.81",
              "1235.14",
              "1227.72",
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "实际电量",
            dataUnit: "万kwh",
          },
          {
            dataTag: "powerForecasting",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "823.09",
              "783.46",
              "882.54",
              "922.17",
              "239.25",
            ],
            dataType: "Line",
            dataName: "预测电量",
            dataUnit: "万kwh",
          },
        ],
      },
    },
    "电镀锌机组": {
      name: "电镀锌机组",
      __type: {
        carbonEmission: "碳排放量情况",
        powerQuantity: "用电情况",
        operatingParameterList: "运行参数情况",
        maintainRecordList: "维护记录",
      },
      maintainRecordList: [
        {
          date: "202301",
          maintainRecord: "333检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202302",
          maintainRecord: "11更换酸液",
          faultDescription: "0%",
        },
        {
          date: "202303",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202304",
          maintainRecord: "更换酸液",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202305",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202306",
          maintainRecord: "清理处理槽",
          faultDescription: "0%",
        },
        {
          date: "202307",
          maintainRecord: "检查酸液浓度",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202308",
          maintainRecord: "更换酸液",
          faultDescription: "0%",
        },
        {
          date: "202309",
          maintainRecord: "检查酸液浓度",
          faultDescription: "0%",
        },
        {
          date: "202310",
          maintainRecord: "更换酸液",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202311",
          maintainRecord: "检查处理设备",
          faultDescription: "1次轻微故障（1小时修复）",
        },
        {
          date: "202312",
          maintainRecord: "年终大修",
          faultDescription: "0%",
        },
      ],
      operatingParameterList: [
        {
          date: "202301",
          ratedPower: "345",
          runningTime: "2.5",
        },
        {
          date: "202302",
          ratedPower: "350",
          runningTime: "2.5",
        },
        {
          date: "202303",
          ratedPower: "55",
          runningTime: "2.5",
        },
        {
          date: "202304",
          ratedPower: "60",
          runningTime: "2.5",
        },
        {
          date: "202305",
          ratedPower: "65",
          runningTime: "2.5",
        },
        {
          date: "202306",
          ratedPower: "70",
          runningTime: "2.5",
        },
        {
          date: "202307",
          ratedPower: "75",
          runningTime: "2.5",
        },
        {
          date: "202308",
          ratedPower: "65",
          runningTime: "2.5",
        },
        {
          date: "202309",
          ratedPower: "70",
          runningTime: "2.5",
        },
        {
          date: "202310",
          ratedPower: "55",
          runningTime: "2.5",
        },
        {
          date: "202311",
          ratedPower: "45",
          runningTime: "2.5",
        },
        {
          date: "202312",
          ratedPower: "65",
          runningTime: "2.5",
        },
      ],
      carbonEmission: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "carbonEmissions",
            dataList: [
              "3607.99",
              "2817.65",
              "3676.67",
              "3195.61",
              "3023.83",
              "3023.83",
              "3264.37",
              "3161.26",
              "3092.58",
              "3264.37",
              "3333.11",
              "3882.87",
            ],
            dataType: "Bar",
            dataName: "碳排放量",
            dataUnit: "吨",
          },
          {
            dataTag: "yoy",
            dataList: [
              Math.random() * 10,
              -11,
              Math.random() * 10,
              Math.random() * 10,
              Math.random() * 10,
              -10.2,
              Math.random() * 10,
              Math.random() * 10,
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "同比",
            dataUnit: "%",
          },
        ],
      },
      powerQuantity: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "power",
            dataList: [
              "1259.89",
              "1202.96",
              "1264.84",
              "1230.18",
              "1217.81",
              "1217.81",
              "1235.14",
              "1227.72",
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "实际电量",
            dataUnit: "万kwh",
          },
          {
            dataTag: "powerForecasting",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "823.09",
              "783.46",
              "882.54",
              "922.17",
              "239.25",
            ],
            dataType: "Line",
            dataName: "预测电量",
            dataUnit: "万kwh",
          },
        ],
      },
    },
  };
  return {
    code: 0,
    msg: "调用成功",
    data: wholedata[params.name],
  };
}
