export function generateResponse() {
  return {
    test2: Math.round(Math.random() * 1000),
    code: 0,
    msg: "13调用成功",
    data: {
      __type: {
        carbonEmissions: "碳排放量情况",
        carbonEmissionsProportion: "碳排占比",
        energyFlowAnalysis: "工序能流分析",
        carbonEmissionsForecasting: "碳排放预测分析",
        powerProduction: "电量-产量情况",
        powerQuantity: "电量预测分析",
      },
      overview: {
        carbonEmissions: 256122.63,
        carbonEmissionsYoy: null,
        energyConsumption: 68334.0,
        energyConsumptionYoy: null,
        power: 22689.56,
        powerYoy: null,
        carbonEmissionsDetailedList: [
          {
            procedureType: "电镀锌(精整)",
            carbonEmissions: 39510.72,
          },
          {
            procedureType: "酸轧",
            carbonEmissions: 168101.67,
          },
          {
            procedureType: "连退",
            carbonEmissions: 58541.24,
          },
        ],
        powerDetailedList: [
          {
            procedureType: "电镀锌(精整)",
            energyConsumption: 2834.06,
          },
          {
            procedureType: "酸轧",
            energyConsumption: 18894.8,
          },
          {
            procedureType: "连退",
            energyConsumption: 960.7,
          },
        ],
      },
      powerProduction: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "electricity",
            dataList: [
              "2080.7",
              "1624.93",
              "2120.33",
              "1842.89",
              "1743.83",
              "1743.83",
              "1882.54",
              "1823.09",
              "1783.46",
              "1882.54",
              "1922.17",
              "2239.25",
            ],
            dataType: "Bar",
            dataName: "电力",
            dataUnit: "万kwh",
          },
          {
            dataTag: "production",
            dataList: [
              "277595.73",
              "216789.06",
              "282883.28",
              "245870.5",
              "232651.69",
              "232651.69",
              "251158.05",
              "243226.74",
              "237939.2",
              "251158.05",
              "256445.59",
              "298745.91",
            ],
            dataType: "Line",
            dataName: "产量",
            dataUnit: "吨",
          },
        ],
      },
      carbonEmissions: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "carbonEmissions",
            dataList: [
              "24407.01",
              "19060.89",
              "24872.06",
              "21617.73",
              "20455.44",
              "20455.44",
              "22082.64",
              "21385.34",
              "20920.23",
              "22082.64",
              "22547.49",
              "26266.72",
            ],
            dataType: "Bar",
            dataName: "碳排放量",
            dataUnit: "吨",
          },
          {
            dataTag: "yoy",
            dataList: [
              Math.random() * 10,
              -11,
              Math.random() * 10,
              Math.random() * 10,
              Math.random() * 10,
              -10.2,
              Math.random() * 10,
              Math.random() * 10,
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "同比",
            dataUnit: "%",
          },
        ],
      },
      carbonEmissionsProportion: [
        {
          carbonEmissionsType: "间接碳排放量",
          carbonEmissionsPercentage: "59.67%",
        },
        {
          carbonEmissionsType: "直接碳排放量",
          carbonEmissionsPercentage: "40.33%",
        },
      ],
      carbonEmissionsForecasting: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "practical",
            dataList: [
              "24407.01",
              "19060.89",
              "24872.06",
              "21617.73",
              "20455.44",
              "20455.44",
              "22082.64",
              "21385.34",
              "20920.23",
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "实际碳排",
            dataUnit: "吨",
          },
          {
            dataTag: "prediction",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "20920.23",
              "22082.64",
              "22547.49",
              "26266.72",
            ],
            dataType: "Line",
            dataName: "预测碳排",
            dataUnit: "吨",
          },
          {
            dataTag: "predictionUpper",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "26920.23",
              "26082.64",
              "26547.49",
              "21266.72",
            ],
            dataType: "Line",
            dataName: "预测上限",
            dataUnit: "吨",
          },
          {
            dataTag: "predictionLower",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "21920.23",
              "20082.64",
              "20547.49",
              "20266.72",
            ],
            dataType: "Line",
            dataName: "预测下限",
            dataUnit: "吨",
          },
        ],
      },
      energyFlowAnalysis: [
        {
          procedureType: "酸轧",
          energyList: [
            {
              energyName: "电力",
              energyConsumption: 18894.8,
              energyUnit: null,
              conversionValue: 23221.7,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "热力",
              energyConsumption: 230480.27,
              energyUnit: null,
              conversionValue: 7863.98,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "焦炉煤气",
              energyConsumption: 1329.74,
              energyUnit: null,
              conversionValue: 7883.37,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "高炉煤气",
              energyConsumption: 2329.68,
              energyUnit: null,
              conversionValue: 2995.98,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "其他",
              energyConsumption: 558955.91,
              energyUnit: null,
              conversionValue: 26.7,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "二级除盐水",
              energyConsumption: 193733.22,
              energyUnit: null,
              conversionValue: 100.01,
              conversionUnit: "吨标准煤",
            },
          ],
        },
        {
          procedureType: "连退",
          energyList: [
            {
              energyName: "电力",
              energyConsumption: 960.7,
              energyUnit: null,
              conversionValue: 1180.7,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "热力",
              energyConsumption: 25872.41,
              energyUnit: null,
              conversionValue: 882.75,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "焦炉煤气",
              energyConsumption: 1237.67,
              energyUnit: null,
              conversionValue: 7337.52,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "高炉煤气",
              energyConsumption: 3649.57,
              energyUnit: null,
              conversionValue: 4693.34,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "二级除盐水",
              energyConsumption: 99122.55,
              energyUnit: null,
              conversionValue: 51.21,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "其他",
              energyConsumption: 1.025508614e7,
              energyUnit: null,
              conversionValue: 950.98,
              conversionUnit: "吨标准煤",
            },
          ],
        },
        {
          procedureType: "电镀锌/精整",
          energyList: [
            {
              energyName: "电力",
              energyConsumption: 960.7,
              energyUnit: null,
              conversionValue: 1180.7,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "热力",
              energyConsumption: 25872.41,
              energyUnit: null,
              conversionValue: 882.75,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "焦炉煤气",
              energyConsumption: 1237.67,
              energyUnit: null,
              conversionValue: 7337.52,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "高炉煤气",
              energyConsumption: 3649.57,
              energyUnit: null,
              conversionValue: 4693.34,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "二级除盐水",
              energyConsumption: 99122.55,
              energyUnit: null,
              conversionValue: 51.21,
              conversionUnit: "吨标准煤",
            },
            {
              energyName: "其他",
              energyConsumption: 1.025508614e7,
              energyUnit: null,
              conversionValue: 950.98,
              conversionUnit: "吨标准煤",
            },
          ],
        },
      ],
      powerQuantity: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "practicalPower",
            dataList: [
              "2080.7",
              "1624.93",
              "2120.33",
              "1842.89",
              "1743.83",
              "1743.83",
              "1882.54",
              "1823.09",
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "实际电量",
            dataUnit: "万kwh",
          },
          {
            dataTag: "predictionPower",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "1823.09",
              "1783.46",
              "1882.54",
              "1922.17",
              "2239.25",
            ],
            dataType: "Line",
            dataName: "预测电量",
            dataUnit: "万kwh",
          },
        ],
      },
    },
  };
}

