export function generateResponse() {
  return {
    code: 0,
    test3: Math.round(Math.random() * 1000),
    msg: "调用成功",
    data: {
      __type: {
        carbonEmissions: "碳排放量情况",
        carbonEmissionsForecasting: "碳排预测分析",
        carbonEmissionsProportion: "设备机组碳排占比",
        powerQuantity: "用电情况",
      },
      overview: {
        carbonEmissions: 39511.72,
        carbonEmissionsYoy: null,
        energyConsumption: 11145.76,
        energyConsumptionYoy: -22,
        power: 2834.06,
        powerYoy: null,
        carbonEmissionsDetailedList: [
          {
            equipmentName: "本浦冷轧3#重卷机组",
            carbonEmissions: 47.41,
          },
          {
            equipmentName: "电镀锌机组",
            carbonEmissions: 39344.14,
          },
          {
            equipmentName: "本浦冷轧2#重卷机组",
            carbonEmissions: 119.17,
          },
        ],
        powerDetailedList: [
          {
            equipmentName: "电镀锌机组",
            energyConsumption: 2808.5,
          },
          {
            equipmentName: "本浦冷轧3#重卷机组",
            energyConsumption: 7.56,
          },
          {
            equipmentName: "本浦冷轧2#重卷机组",
            energyConsumption: 18.0,
          },
        ],
      },
      carbonEmissions: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "carbonEmissions",
            dataList: [
              "3623.25",
              "2829.57",
              "3692.25",
              "3209.1",
              "3036.61",
              "3036.61",
              "3278.19",
              "3174.67",
              "3105.68",
              "3278.19",
              "3347.25",
              "3899.35",
            ],
            dataType: "Bar",
            dataName: "碳排放量",
            dataUnit: "吨",
          },
          {
            dataTag: "yoy",
            dataList: [
              Math.random() * 10,
              -11,
              Math.random() * 10,
              Math.random() * 10,
              Math.random() * 10,
              -10.2,
              Math.random() * 10,
              Math.random() * 10,
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "同比",
            dataUnit: "%",
          },
        ],
      },
      carbonEmissionsProportion: [
        {
          equipmentName: "本浦冷轧3#重卷机组",
          carbonEmissionsPercentage: "0.12%",
        },
        {
          equipmentName: "电镀锌机组",
          carbonEmissionsPercentage: "99.58%",
        },
        {
          equipmentName: "本浦冷轧2#重卷机组",
          carbonEmissionsPercentage: "0.30%",
        },
      ],
      carbonEmissionsForecasting: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "practical",
            dataList: [
              "3623.25",
              "2829.57",
              "3692.25",
              "3209.1",
              "3036.61",
              "3036.61",
              "3278.19",
              "3174.67",
              "3623.25",
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "实际碳排",
            dataUnit: "吨",
          },
          {
            dataTag: "prediction",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "3623.25",
              "3036.61",
              "3278.19",
              "3174.67",
            ],
            dataType: "Line",
            dataName: "预测碳排",
            dataUnit: "吨",
          },
          {
            dataTag: "predictionUpper",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "3823.25",
              "3236.61",
              "3478.19",
              "3374.67",
            ],
            dataType: "Line",
            dataName: "预测上限",
            dataUnit: "吨",
          },
          {
            dataTag: "predictionLower",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "3323.25",
              "2836.61",
              "3078.19",
              "2974.67",
            ],
            dataType: "Line",
            dataName: "预测下限",
            dataUnit: "吨",
          },
        ],
      },
      powerQuantity: {
        xList: [
          "01月",
          "02月",
          "03月",
          "04月",
          "05月",
          "06月",
          "07月",
          "08月",
          "09月",
          "10月",
          "11月",
          "12月",
        ],
        yList: [
          {
            dataTag: "power",
            dataList: [
              "1259.89",
              "1202.96",
              "1264.84",
              "1230.18",
              "1217.81",
              "1217.81",
              "1235.14",
              "1227.72",
              null,
              null,
              null,
              null,
            ],
            dataType: "Line",
            dataName: "实际电量",
            dataUnit: "万kwh",
          },
          {
            dataTag: "powerForecasting",
            dataList: [
              null,
              null,
              null,
              null,
              null,
              null,
              null,
              "823.09",
              "783.46",
              "882.54",
              "922.17",
              "239.25",
            ],
            dataType: "Line",
            dataName: "预测电量",
            dataUnit: "万kwh",
          },
        ],
      },
    },
  };
}



