/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElMessage: typeof import('element-plus/es')['ElMessage']
}
// interface RuntimeConfig {
//   API_URL: string;
//   FEATURE_FLAG: boolean;
// }

// declare global {
//   interface Window {
//     __RUNTIME_CONFIG__: RuntimeConfig;
//   }
// }
